### ISSUE TITLE
Create a Markdown notebook for the original siQ-ChIP implementation (installation, usage, etc.), and run it for reproducibility and integration tests

### ISSUE THREAD

**Issue by kalavattam** [kalavattam/protocol_chipseq_signal_norm#3]
**Overview**  
  
To ensure that the computation of alpha and normalized coverage in this project aligns with [Brad's original siQ-ChIP implementation](https://github.com/kalavattam/siQ-ChIP/tree/cerevisiae), we need to create a Markdown notebook that describes the installation and usage instructions for Brad's siQ-ChIP code. The outputs from running Brad’s implementation will serve two purposes:
1. Verify that the [_protocol_chipseq_signal_norm_](https://github.com/kalavattam/protocol_chipseq_signal_norm) computations (i.e., alpha values and normalized coverage tracks) are consistent with the original siQ-ChIP implementation.
2. To validate reproducibility and accuracy of the new Python implementations, use outputs as a standard reference for integration tests of [_protocol_chipseq_signal_norm_](https://github.com/kalavattam/protocol_chipseq_signal_norm) scripts.
<br />

**Tasks**  
- [x] Identify and document all installation requirements for [Brad's siQ-ChIP implementation](https://github.com/kalavattam/siQ-ChIP/tree/cerevisiae) (e.g., dependencies, compilation instructions, etc.).
- [x] Write usage instructions for running the implementation, including expected inputs (e.g., BAM-derived TSV files, metadata) and outputs (e.g., alpha values, coverage tracks).
- [x] Generate example outputs from Brad’s implementation using a test dataset.
- [x] To verify accuracy/reproducibility of alpha and normalized coverage computations, compare outputs with results from the new Python implementations <mark>_prior to the refactoring described in [Issue #2](https://github.com/kalavattam/protocol_chipseq_signal_norm/issues/2)_</mark>.
    + [x] Based on the comparison results, move forward with [Issue #2](https://github.com/kalavattam/protocol_chipseq_signal_norm/issues/2) or not.
    + [x] The above entails completing [Issue #1](https://github.com/kalavattam/protocol_chipseq_signal_norm/issues/1) first.
- [ ] Update this notebook with any troubleshooting tips or observations from the testing process.
- [ ] Incorporate the notebook into the repository as a reference for users and collaborators.
- [ ] Use the notebook to write instructions in the manuscript's supplemental materials.
